### ISSUE TITLE
question for PRx to know root CA 

### ISSUE THREAD

**Issue by davesliu** [Infineon/wpcqi-optiga-trust-charge#2]
Hello

How did PRx know the root CA qi_auth_ifx_root_cert as shown in below line?

is the qi_auth_ifx_root_cert downloaded from CA web page and burn it into PRx firmware?

From the WPC 1.3 authentication, the PTx side only send the certification chain (with root CA digest,  Manufacture CA and Producation CA).  So how PRx get the root CA certification?

https://github.com/Infineon/wpcqi-optiga-trust-charge/blob/5c063574f14e521916a5f74339d92fed1a3bb31c/wpc/qi_auth_self_test.c#L114

**Comment by ShaikKarishma0** [comment]
Hi @davesliu,

As mentioned in the [description](https://github.com/Infineon/wpcqi-optiga-trust-charge/tree/master#description), this code example is partial implementation of the WPC QI 1.3 authentication flow. It is just for getting started with the various function calls with respect to PTx and PRx. Hence, the value of qi_auth_ifx_root is hardcoded. 

To implement the actual flow of certificate verification, you need to parse the certificate chain to extract the device certificate, intermediate CA certificate and root CA digest, and then verify the root of trust.

Regards,
Karishma

**Comment by davesliu** [comment]
@ShaikKarishma0  
Thanks for your info
BTW,   I saw that it uses mbedtls library on Rx side to parse the X.509 certification chain.  
In fact, the mbedtls library is too large, even I customized many unrelated features. It still takes more than 300KB space, as the Rx chip generally take 32KB flash or even less. So how did Infineon deal with the mbedtls library on Rx side?  does it use another AP to deal with it?

**Comment by ayushev** [comment]
Please have a look on our configuration, in the maximum configuration with all the features it takes max 25 kBytes, there is, however also potential for further optimization

**Comment by davesliu** [comment]
@ayushev  Thanks for your info.
I used mbedtls version 1.80 from MKD uversion 5 and do some customization by myself. 
I will follow the link above.

BTW, which version of mbedtls in above link is originated from?

**Comment by ayushev** [comment]
It is [2.16.0](https://github.com/Infineon/optiga-trust-charge/blob/54f5f30662e28f6ec67d397010b8f7f450879843/externals/mbedtls/include/mbedtls/version.h#L41-L43)

**Comment by davesliu** [comment]
@ayushev  thanks :-) 
For your previous saying 25KB, do you mean it is the binary size, not the lib size?

**Comment by ayushev** [comment]
I was referring to [this](https://github.com/Infineon/optiga-trust-charge/blob/54f5f30662e28f6ec67d397010b8f7f450879843/documents/Code_Footprint.md) document, it is a FLASH size consumed by the package

**Comment by davesliu** [comment]
@ayushev  Above link is for Tx side usage.
How about the size for Rx side?
Have you do some test for it?
As you knew that the Rx side may take more size for the mbedtls library.

**Comment by ShaikKarishma0** [comment]
Hi @davesliu,

Flash size of mbedtls library on Rx side is ~27KB for optiga_prx_crypto build configuration and ~32KB for software_prx_crypto build configuration. We have used the [amap](https://www.sikorskiy.net/info/prj/amap/#download) tool to calculate flash size.

Note: change the optimization level to optimize for size (-Os) in the project properties for above results

**Comment by davesliu** [comment]
@ShaikKarishma0 
Thanks for your info. I use STM32 and its size is more than 50KB....
