### ISSUE TITLE
question for public key size

### ISSUE THREAD

**Issue by davesliu** [Infineon/wpcqi-optiga-trust-charge#3]
Hello

For the product unit public key, I saw that the size is defined as 68.
https://github.com/Infineon/wpcqi-optiga-trust-charge/blob/5c063574f14e521916a5f74339d92fed1a3bb31c/wpc/qi_auth_self_test.c#L51

But from the function comments. It said that  the size is 65 as shown below. So I'm a little confused about the size. 
Could you help to explain it? 

Thanks a lot 

* \param p_puc_pubkey_size[in][out] Size of the public key in the Product Unit Certificate.
*                               Should fit PubKeyLength(uncopressed 64) + Compression Byte[1]
*

**Comment by ShaikKarishma0** [comment]
Hi @davesliu,

The defined size of 68 just allocates some extra bytes to the public key buffer. However, the qi_auth_prx_get_certchain_info() function copies only the required 65 bytes (compression byte + key value) into the buffer and rest of the bytes have garbage value. You can see that this function also returns the pubkey buffer size as 65. Therefore you can change the buffer size to 65 and this will not have any effect on the implementation.

**Comment by davesliu** [comment]
But in fact, if you look at the source code of  mbedtls_ecp_point_write_binary
https://github.com/Infineon/wpcqi-optiga-trust-charge/blob/5c063574f14e521916a5f74339d92fed1a3bb31c/wpc/PRx/qi_auth_prx_crypt.c#L572

The length 68 is used. ...

**Comment by ShaikKarishma0** [comment]
Yes, the predefined value is passed to the function. But, as this function is used to copy the uncompressed form of public key into the buffer, it updates the buffer and its size variable accordingly. Therefore, the buffer size value will get updated to 65 after the execution of  mbedtls_ecp_point_write_binary function.

**Comment by davesliu** [comment]
@ShaikKarishma0 
Thanks for your detail explaination. :-)
