### ISSUE TITLE
question about the convert between ECDSA R|S value and ASN1

### ISSUE THREAD

**Issue by davesliu** [Infineon/wpcqi-optiga-trust-charge#4]
Hello

I saw that on Tx side, it converterd the signed data from format ASN1 to R|S on Tx side. So why don't the chip send R|S value directly to Tx?

By the way, as Rx side will convert the R|S value to ASN1 for signature verification. Why don't Tx side send ASN1 data instead of R|S info in the authen_response message from Tx to Rx?

I saw that the WPC 1.3 standard requres Tx to send ECDSA R|S value to Rx. Why not send ASN1 data?
If sending ASN1 data, so both Tx/Rx side doesn't need to convert the the R|S data.

**Comment by ShaikKarishma0** [comment]
Hi @davesliu,

R|S is the smallest representation of the signature which consumes the least amount of bytes for transmission and is very efficient in case of wireless transmission.

As different vendors have different formats, WPC Qi Auth Specification concluded to use the most effective representation for their own use.

**Comment by davesliu** [comment]
Got it, so we need extra function to convert it.
