### ISSUE TITLE
issue for implementing random number on Rx side

### ISSUE THREAD

**Issue by davesliu** [Infineon/wpcqi-optiga-trust-charge#5]

**Comment by davesliu** [comment]
Hello

When I use the example code of qi_auth_prx_crypt_get_random() to generate random data, it always failed.


https://github.com/Infineon/wpcqi-optiga-trust-
charge/blob/5c063574f14e521916a5f74339d92fed1a3bb31c/wpc/PRx/qi_auth_prx_crypt.c#L652

**Comment by ShaikKarishma0** [comment]
Hi @davesliu,

Can you please provide more info on this, where exactly are you calling this function?

**Comment by davesliu** [comment]
@ShaikKarishma0 

When I use the example code of qi_auth_prx_crypt_get_random() in qi_auth_prx_crypt_soft.c to generate random data, it always failed.

https://github.com/Infineon/wpcqi-optiga-trust-charge/blob/5c063574f14e521916a5f74339d92fed1a3bb31c/wpc/PRx/qi_auth_prx_crypt_soft.c#L342

I searched on google, it shows that the mbedtls_entropy_init() and mbedtls_ctr_drbg_seed() should be used, which need to enable some macro definition such as MBEDTLS_ENTROPY_C  MBEDTLS_AES_ROM_TABLES MBEDTLS_ENTROPY_FORCE_SHA256

Could you help to check if it is an issue?

**Comment by ShaikKarishma0** [comment]
Please uncomment '[MBEDTLS_CTR_DRBG_C](https://github.com/Infineon/optiga-trust-charge/blob/54f5f30662e28f6ec67d397010b8f7f450879843/externals/mbedtls/include/mbedtls/config.h#L2107)' and  '
[MBEDTLS_AES_C](https://github.com/Infineon/optiga-trust-charge/blob/54f5f30662e28f6ec67d397010b8f7f450879843/externals/mbedtls/include/mbedtls/config.h#L1819)' definition in the mbedtls configuration file and try to execute the qi_auth_prx_crypt_get_random() function.

**Comment by davesliu** [comment]
@ShaikKarishma0 
In fact, I had uncomment both macro definitions. Otherwise it will have compilation error due to dependency.
Per my understanding, it needs to use mbedtls_entropy_init() and mbedtls_ctr_drbg_seed() to prepare for random generation.
So I think the example code in [wpcqi-optiga-trust-charge](https://github.com/Infineon/wpcqi-optiga-trust-charge) may not work

**Comment by davesliu** [comment]
@ShaikKarishma0
Have you tried the usage of mbedtls_ctr_drbg_random successfully without enable MBEDTLS_ENTROPY_C MBEDTLS_AES_ROM_TABLES MBEDTLS_ENTROPY_FORCE_SHA256？

**Comment by ShaikKarishma0** [comment]
Hi @davesliu,

I'm working on it. Will get back to you on this.

**Comment by ShaikKarishma0** [comment]
Hi @davesliu,

The mbedtls_ctr_drbg_random() function executes successfully without any changes. 

<img width="712" alt="random_num_trust_charge" src="https://user-images.githubusercontent.com/98537298/192979343-8dfbc343-e870-45fb-8489-ad784810a804.png">

**Comment by davesliu** [comment]
@ShaikKarishma0 
Did you use the default config.h file ?
On my side, it always failed. I use STM32F106 platform. Not the X86 platform.

**Comment by ShaikKarishma0** [comment]
Hi @davesliu,

Yes, I have used the default config.h file. 

Can you please try using the default config.h file without any changes and if the function still fails then please share the error message displayed.

**Comment by davesliu** [comment]
@ShaikKarishma0 
For default config.h usage. did you use it on X86 platform or embedded system platform?

Have you use  mbedtls_ctr_drbg_seed() function to generate seed for your above snapshot?

In fact, I didn't see the  mbedtls_ctr_drbg_seed() usage in the example code of this example repo.

**Comment by ShaikKarishma0** [comment]
Hi @davesliu,

> For default config.h usage. did you use it on X86 platform or embedded system platform?

I have implemented the functionality on trust charge evaluation kit which comes with XMC4700 microcontroller, which is based on ARM cortex architecture (not X86).


> Have you use mbedtls_ctr_drbg_seed() function to generate seed for your above snapshot?
> 
> In fact, I didn't see the mbedtls_ctr_drbg_seed() usage in the example code of this example repo.

The mbedtls_ctr_drbg_reseed() function is directly called within mbedtls_ctr_drbg_random_with_add() function. This function reseeds the CTR_DRBG context, that is extracts data from the entropy source. 



> Just now, I saw the example code works. But found that each time, the random value is same... How to generate real random value each time?

Please refer to the changes made in [this](https://github.com/Infineon/wpcqi-optiga-trust-charge/compare/ayushev-rng). With these changes you can generate a different value but please keep in mind, it will always return deterministic random value. That is, every time you call the function 'mbedtls_ctr_drbg_random()', it will return a different value, but you can always predict the value if you call it in the same time.

**Comment by davesliu** [comment]
@ShaikKarishma0 
It's helpful. Thanks.
