### ISSUE TITLE
Question for the ecdsa_rs_to_asn1 convert functions

### ISSUE THREAD

**Issue by davesliu** [Infineon/wpcqi-optiga-trust-charge#6]
Hello

I saw it defines the ecdsa_rs_to_asn1_signature()/asn1_to_ecdsa_rs() for converter between rs and ans1 in eadc_utils.c
In fact, it already has functions ecdsa_signature_to_asn1() in ecdas.c of mbedtls. Why not use ecdsa_signature_to_asn1() directly on Rx side?

**Comment by ShaikKarishma0** [comment]
Hi @davesliu,

The functions 'ecdsa_rs_to_asn1_signature()' / 'asn1_to_ecdsa_rs()' present in ecdsa_utils.c are used to perform corresponding crypto functionalities on optiga chip of Tx. [ Eg. In this function 'qi_auth_ptx_challenge_auth()' ]

On the other hand, the function 'ecdsa_signature_to_asn1()' is used in software implementation of the crypto functionalities on Rx side, that is when you use mbedtls on Rx side. [ Eg. In this function 'qi_auth_prx_get_certchain_info()' ]

**Comment by davesliu** [comment]
Thanks for your info. :-)
