### ISSUE TITLE
timing cost for verification of signature and certification.

### ISSUE THREAD

**Issue by davesliu** [Infineon/wpcqi-optiga-trust-charge#8]
Hello

I use  code on SMT32F103 platform to parse the test cert chain in this project, found that it take about 8 seconds to verify the certification ( ROOT verify manufacturer), and the verification of signature also take about 8 seconds. It seems too slow.

Do you have some suggestion to speed up the verification process?

Thanks

**Comment by ShaikKarishma0** [comment]
Hi @davesliu,

I am using XMC4700 relax kit which works on 144MHz frequency for implementing the ECC signature verification functionality, and it provides the following values:

- In non-optimized mode, it takes ~5 seconds 
- In other optimization modes (Ex. -O1,-O2), it takes ~2.5 seconds

As you can see, the speed of execution has almost doubled by using the optimization modes.

Please check the frequency at which your platform works. Try to optimize using various modes and see which best suits your application.

Regards,
Karishma

**Comment by davesliu** [comment]
Thanks a lot. :-)
I will try with optimization options.
